Multi/release v1.0.1
plentymarkets/plugin-elastic-export-billiger-de pull request #1
Opened 2017-07-12 08:38 UTC by alinmigea

@plentymarkets/team-multichannel-koboldmaki

2017-07-12 09:34 UTC, mariusbippig requested changes

2017-07-12 09:34 UTC, Desentyer commented on meta/documents/changelog_de.md
> +- Zusätzliche Felder in der Export-csv-Datei hinzugefügt, um die zusätzlichen Eigenschaften für billiger.de zugänglich zu machen.
Die Felder der CSV-Datei wurden erweitert, um neue Merkmale für billiger.de zu unterstützen.

2017-07-12 09:34 UTC, Desentyer commented on meta/documents/changelog_en.md
> +- Added optional fields in the export csv file to provide the extra properties needed for billiger.de.
The fields of the CSV file were extended to support new properties for billiger.de.

2017-07-12 09:34 UTC, Desentyer commented on src/Generator/BilligerDE.php
> +            $variationRetailPrice['variationRetailPrice.price'] = $priceList['price'];
You don't need to set that in a new variable. Just use $priceList

2017-07-12 09:34 UTC, Desentyer commented on src/Generator/BilligerDE.php
> +                'ppu'           => $this->elasticExportHelper->getBasePrice($variation, $variationRetailPrice, $settings->get('lang')),
There is now a ElasticExportPriceHelper, use that instead of base helper pls.

2017-07-12 09:34 UTC, Desentyer commented on src/Helper/PropertyHelper.php
> +    private function getItemPropertyList($variation, $lang):array
Why have you converted the optional parameter to a required one?

2017-07-14 08:05 UTC, mariusbippig approved these changes

2017-07-17 08:29 UTC, hschwab approved these changes

2017-07-17 14:28 UTC, merged