RELEASE v1.0.6
plentymarkets/plugin-elastic-export-billiger-de pull request #6
Opened 2017-10-24 14:36 UTC by alinmigea

ADD the delivery to SOP field in the CSV export
ADD the stock quantity field needed for the SOP market
REMOVE the extra logs that were not needed anymore

2017-10-24 14:51 UTC, alinmigea commented
@plentymarkets/team-multichannel-koboldmaki 

Please take a look at the [UI PR](https://github.com/plentymarkets/php-ps/pull/2040) with this property

2017-10-25 07:27 UTC, hschwab approved these changes

2017-10-25 07:43 UTC, mbrueschke requested changes

2017-10-25 07:43 UTC, mbrueschke commented on src/Generator/BilligerDE.php
> +                'delivery_sop'      => $this->elasticExportPropertyHelper->getProperty($variation, 'delivery_sop', self::BILLIGER_DE, $settings->get('lang')),
pls make delivery_sop a constant. 
also just check if it was set. it does not need to have a value

2017-10-26 06:38 UTC, mbrueschke approved these changes

2017-10-26 11:40 UTC, merged